apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sippy
  namespace: sippy
  labels:
    app: sippy
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: standard
