apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: release-triage-k8s-io
  namespace: triageparty-release
  labels:
    app: triage-party
spec:
  domains:
    - release.triage.k8s.io
