apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: triage-party-github-token
  namespace: triageparty-release
  labels:
    app: triage-party
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
  - key: triage-party-github-token
    name: token
    version: latest
