apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: triage-party-persistence
  namespace: triageparty-release
  labels:
    app: triageparty
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ssd
