kind: Service
apiVersion: v1
metadata:
  name: slack-moderator
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  selector:
    app: slack-moderator
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
