apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: slack-moderator-words-config  # The name of the Kubernetes Secret
  namespace: slack-infra
  labels:
    app: slack-moderator-words
spec:
  backendType: gcpSecretsManager
  projectId: kubernetes-public
  data:
  - key: slack-moderator-words-config # The name of the GSM secret
    name: config.json                 # The key to write to in the Kubernetes Secret
    version: latest                   # The version of the GSM secret
