apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    iam.gke.io/gcp-service-account: k8s-infra-prow@kubernetes-public.iam.gserviceaccount.com
  namespace: prow
  name: deck
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: deck
rules:
- apiGroups:
  - "prow.k8s.io"
  resources:
  - prowjobs
  verbs:
  - get
  - list
  - watch
  # Required when deck runs with `--rerun-creates-job=true`
  - create
- apiGroups:
  - ""
  resources:
  - pods/log
  verbs:
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: prow
  name: deck
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: deck
subjects:
- kind: ServiceAccount
  name: deck
