apiVersion: v1
kind: ServiceAccount
metadata:
  name: kettle
  namespace: kettle
  labels:
    app: kettle
  annotations:
    iam.gke.io/gcp-service-account: kettle@kubernetes-public.iam.gserviceaccount.com
